export * from "./Home/Home";
export * from "./SignUp/Opt";
export * from "./MyBag/MyBag";
export * from "./LogIn/LogIn";
export * from "./Order/Order";
export * from "./SignUp/SignUp";
export * from "./Profile/Profile";
export * from "./Payment/Payment";
export * from "./Detail/DetailSection";